# -*- coding: utf-8 -*-
"""Project-level runner for the 2025 PV day-ahead forecasting project.

This script keeps the original experiment scripts intact and provides a
single switch-style entry point for running or inspecting selected workflow
links. Most main links are independent; only the scenario attribution link
depends on prediction tables generated by the historical baseline and NWP
forecast fusion links.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


ROOT = Path(__file__).resolve().parent
UTF8_SIG = "utf-8-sig"


@dataclass(frozen=True)
class ProjectTask:
    key: str
    title: str
    description: str
    scripts: tuple[Path, ...]
    output_dir: Path
    reports: tuple[Path, ...] = ()
    metrics: tuple[Path, ...] = ()
    predictions: tuple[Path, ...] = ()
    required_outputs: tuple[Path, ...] = ()
    depends: tuple[str, ...] = ()


@dataclass(frozen=True)
class ScriptRun:
    script: Path
    returncode: int
    elapsed_seconds: float
    output: str = ""


@dataclass(frozen=True)
class TaskRun:
    key: str
    elapsed_seconds: float
    script_runs: tuple[ScriptRun, ...]


P1_DIR = ROOT / "02_problem_solutions" / "problem1_data_analysis"
P2_DIR = ROOT / "02_problem_solutions" / "problem2_baseline_forecasting"
P3_DIR = ROOT / "02_problem_solutions" / "problem3_scenario_analysis"
P4_DIR = ROOT / "02_problem_solutions" / "problem4_feature_ablation"

TASKS: dict[str, ProjectTask] = {
    "1": ProjectTask(
        key="1",
        title="站点机理诊断",
        description="运行三个 Python 理论功率入口，生成理论功率、指标和诊断图。",
        scripts=(
            P1_DIR / "theoretical_power_baseline.py",
            P1_DIR / "theoretical_power_calculation.py",
            P1_DIR / "theoretical_power_diagnostics.py",
        ),
        output_dir=P1_DIR / "outputs",
        reports=(P1_DIR / "outputs" / "reports" / "run_summary.json",),
        metrics=(
            P1_DIR / "outputs" / "metrics" / "problem1_daylight_error_metrics.csv",
            P1_DIR / "outputs" / "metrics" / "problem1_monthly_power_stats.csv",
            P1_DIR / "outputs" / "metrics" / "problem1_relative_error_statistics.csv",
        ),
        predictions=(P1_DIR / "outputs" / "predictions" / "problem1_theoretical_power_timeseries.csv",),
        required_outputs=(P1_DIR / "outputs" / "reports" / "run_summary.json",),
    ),
    "2": ProjectTask(
        key="2",
        title="历史功率基线",
        description="运行历史功率序列三模型预测，并生成指标、图和预测表。",
        scripts=(P2_DIR / "problem2_baseline_three_model_forecast.py",),
        output_dir=P2_DIR / "outputs",
        reports=(P2_DIR / "outputs" / "reports" / "run_summary.json",),
        metrics=(P2_DIR / "outputs" / "metrics" / "三模型白昼指标对比.csv",),
        predictions=(P2_DIR / "outputs" / "predictions" / "三模型预测结果对比表.csv",),
        required_outputs=(P2_DIR / "outputs" / "predictions" / "三模型预测结果对比表.csv",),
    ),
    "3": ProjectTask(
        key="3",
        title="气象预报融合",
        description="运行前一日实测功率 + 目标日 NWP 的三模型预测。",
        scripts=(P3_DIR / "problem3_weather_feature_forecast.py",),
        output_dir=P3_DIR / "outputs",
        reports=(P3_DIR / "outputs" / "reports" / "run_summary.json",),
        metrics=(P3_DIR / "outputs" / "metrics" / "三模型白昼指标对比.csv",),
        predictions=(P3_DIR / "outputs" / "predictions" / "3三模型预测结果对比表.csv",),
        required_outputs=(P3_DIR / "outputs" / "predictions" / "3三模型预测结果对比表.csv",),
    ),
    "3-analysis": ProjectTask(
        key="3-analysis",
        title="运行场景归因",
        description="读取历史功率基线与气象预报融合的预测表，生成场景划分、提升来源和典型日解释图表。",
        scripts=(
            P3_DIR / "problem3_scenario_ieee_analysis.py",
            P3_DIR / "problem3_integrated_scenario_analysis.py",
            P3_DIR / "problem3_extended_scenario_analysis.py",
            P3_DIR / "problem3_three_model_curve_plot.py",
        ),
        output_dir=P3_DIR / "outputs",
        reports=(
            P3_DIR / "outputs" / "reports" / "problem3_scenario_ieee_analysis_summary.json",
            P3_DIR / "outputs" / "reports" / "problem3_integrated_scenario_analysis_summary.json",
            P3_DIR / "outputs" / "reports" / "problem3_extended_scenario_analysis_summary.json",
            P3_DIR / "outputs" / "reports" / "problem3_three_model_curve_plot_summary.json",
        ),
        metrics=(
            P3_DIR / "outputs" / "metrics" / "场景划分提升分析结果.csv",
            P3_DIR / "outputs" / "metrics" / "线性回归_提升来源分析.csv",
            P3_DIR / "outputs" / "metrics" / "随机森林_特征重要性.csv",
        ),
        required_outputs=(P3_DIR / "outputs" / "reports" / "problem3_scenario_ieee_analysis_summary.json",),
        depends=("2", "3"),
    ),
    "4": ProjectTask(
        key="4",
        title="局地校正融合",
        description="运行 NWP、LMD、mixed 三类输入的严格日前预测消融。",
        scripts=(P4_DIR / "problem4_feature_ablation_forecast.py",),
        output_dir=P4_DIR / "outputs",
        reports=(P4_DIR / "outputs" / "reports" / "run_summary.json",),
        metrics=(P4_DIR / "outputs" / "metrics" / "Q4_模型输入对比结果.csv",),
        predictions=(
            P4_DIR / "outputs" / "predictions" / "Q4_pred_FusionModel_nwp.csv",
            P4_DIR / "outputs" / "predictions" / "Q4_pred_FusionModel_lmd.csv",
            P4_DIR / "outputs" / "predictions" / "Q4_pred_FusionModel_mixed.csv",
        ),
        required_outputs=(P4_DIR / "outputs" / "metrics" / "Q4_模型输入对比结果.csv",),
    ),
}

ALIASES: dict[str, tuple[str, ...]] = {
    "1": ("1",),
    "q1": ("1",),
    "p1": ("1",),
    "problem1": ("1",),
    "2": ("2",),
    "q2": ("2",),
    "p2": ("2",),
    "problem2": ("2",),
    "3": ("3",),
    "q3": ("3",),
    "p3": ("3",),
    "problem3": ("3",),
    "3-analysis": ("3-analysis",),
    "3_analysis": ("3-analysis",),
    "analysis": ("3-analysis",),
    "scenario": ("3-analysis",),
    "场景": ("3-analysis",),
    "4": ("4",),
    "q4": ("4",),
    "p4": ("4",),
    "problem4": ("4",),
    "main": ("1", "2", "3", "4"),
    "all": ("1", "2", "3", "4", "3-analysis"),
}


def relative(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


def split_selection(raw_items: Sequence[str] | None) -> list[str]:
    if not raw_items:
        return []
    tokens: list[str] = []
    for item in raw_items:
        for token in item.replace("，", ",").split(","):
            token = token.strip()
            if token:
                tokens.append(token)
    return tokens


def parse_task_selection(raw_items: Sequence[str] | None) -> list[str]:
    selected: list[str] = []
    for token in split_selection(raw_items):
        key = token.lower()
        if key not in ALIASES:
            raise ValueError(f"未知任务：{token}。可用任务为 1, 2, 3, 3-analysis, 4, main, all。")
        for task_key in ALIASES[key]:
            if task_key not in selected:
                selected.append(task_key)
    return selected


def task_outputs_ready(task_key: str) -> bool:
    outputs = TASKS[task_key].required_outputs
    return bool(outputs) and all(path.exists() for path in outputs)


def missing_dependency_outputs(task_key: str, selected: set[str]) -> list[tuple[str, Path]]:
    missing: list[tuple[str, Path]] = []
    for dep_key in TASKS[task_key].depends:
        if dep_key in selected:
            continue
        if task_outputs_ready(dep_key):
            continue
        for path in TASKS[dep_key].required_outputs:
            if not path.exists():
                missing.append((dep_key, path))
    return missing


def build_execution_batches(task_keys: Sequence[str], parallel: bool) -> list[list[str]]:
    selected = set(task_keys)
    for task_key in task_keys:
        missing = missing_dependency_outputs(task_key, selected)
        if missing:
            details = "\n".join(f"  - {dep}: {relative(path)}" for dep, path in missing)
            raise RuntimeError(
                f"{TASKS[task_key].title} 需要已有依赖输出，但当前缺失：\n{details}\n"
                "请先运行对应依赖任务，或把依赖任务一起放入 --run。"
            )

    remaining = list(task_keys)
    completed: set[str] = set()
    batches: list[list[str]] = []

    while remaining:
        ready = [
            task_key
            for task_key in remaining
            if all(dep in completed or dep not in selected for dep in TASKS[task_key].depends)
        ]
        if not ready:
            blocked = ", ".join(remaining)
            raise RuntimeError(f"任务依赖无法解析，剩余任务：{blocked}")

        if parallel:
            batch = ready
            batches.append(batch)
            completed.update(batch)
            remaining = [task_key for task_key in remaining if task_key not in batch]
        else:
            task_key = ready[0]
            batches.append([task_key])
            completed.add(task_key)
            remaining.remove(task_key)

    return batches


def build_child_env(args: argparse.Namespace) -> dict[str, str]:
    env = os.environ.copy()
    overrides = {
        "PV_FORCE_RETRAIN": "1" if args.force_retrain else None,
        "PV_FORECAST_EPOCHS": args.epochs,
        "PV_FORECAST_PATIENCE": args.patience,
        "PV_FORECAST_BATCH_SIZE": args.batch_size,
        "PV_FORECAST_HIDDEN_DIM": args.hidden_dim,
        "PV_Q4_MODES": args.q4_modes,
        "PV_Q4_MODELS": args.q4_models,
        "PV_Q4_SAVE_RUN_DIAGNOSTICS": "0" if args.q4_fast else None,
    }
    for name, value in overrides.items():
        if value is not None:
            env[name] = str(value)
    return env


def environment_overrides(args: argparse.Namespace) -> dict[str, str]:
    env = build_child_env(args)
    return {
        name: env[name]
        for name in [
            "PV_FORCE_RETRAIN",
            "PV_FORECAST_EPOCHS",
            "PV_FORECAST_PATIENCE",
            "PV_FORECAST_BATCH_SIZE",
            "PV_FORECAST_HIDDEN_DIM",
            "PV_Q4_MODES",
            "PV_Q4_MODELS",
            "PV_Q4_SAVE_RUN_DIAGNOSTICS",
        ]
        if name in env
    }


def tail_text(text: str, max_lines: int = 40) -> str:
    lines = text.splitlines()
    if len(lines) <= max_lines:
        return text
    omitted = len(lines) - max_lines
    return f"... 省略 {omitted} 行输出 ...\n" + "\n".join(lines[-max_lines:])


def run_script(script: Path, env: dict[str, str], capture_output: bool) -> ScriptRun:
    start = time.time()
    cmd = [sys.executable, "-u", script.name]
    if capture_output:
        completed = subprocess.run(
            cmd,
            cwd=script.parent,
            env=env,
            text=True,
            encoding="utf-8",
            errors="replace",
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        output = completed.stdout or ""
    else:
        completed = subprocess.run(cmd, cwd=script.parent, env=env, check=False)
        output = ""
    return ScriptRun(script=script, returncode=completed.returncode, elapsed_seconds=time.time() - start, output=output)


def run_task(task_key: str, env: dict[str, str], capture_output: bool) -> TaskRun:
    task = TASKS[task_key]
    print(f"\n===== 运行 {task.title} =====", flush=True)
    task_start = time.time()
    script_runs: list[ScriptRun] = []

    for script in task.scripts:
        print(f"-> {relative(script)}", flush=True)
        script_run = run_script(script, env, capture_output=capture_output)
        script_runs.append(script_run)
        if capture_output and script_run.output:
            print(tail_text(script_run.output), flush=True)
        if script_run.returncode != 0:
            raise RuntimeError(
                f"{relative(script)} 运行失败，退出码 {script_run.returncode}。"
            )

    elapsed = time.time() - task_start
    print(f"完成 {task.title}，耗时 {elapsed:.1f} 秒。", flush=True)
    return TaskRun(task_key, elapsed, tuple(script_runs))


def execute_tasks(task_keys: Sequence[str], args: argparse.Namespace) -> list[TaskRun]:
    batches = build_execution_batches(task_keys, parallel=args.parallel)
    env = build_child_env(args)

    if args.dry_run:
        print("计划运行批次：")
        for index, batch in enumerate(batches, start=1):
            print(f"  批次 {index}: {', '.join(batch)}")
        overrides = environment_overrides(args)
        if overrides:
            print("环境变量覆盖：")
            for name, value in overrides.items():
                print(f"  {name}={value}")
        return []

    task_runs: list[TaskRun] = []
    for batch in batches:
        if args.parallel and len(batch) > 1:
            with ThreadPoolExecutor(max_workers=len(batch)) as executor:
                futures = {
                    executor.submit(run_task, task_key, env, True): task_key
                    for task_key in batch
                }
                for future in as_completed(futures):
                    task_runs.append(future.result())
        else:
            task_runs.append(run_task(batch[0], env, capture_output=False))
    return task_runs


def read_json(path: Path) -> dict[str, object] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def read_csv_rows(path: Path, max_rows: int = 8) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding=UTF8_SIG, newline="") as handle:
        reader = csv.DictReader(handle)
        rows: list[dict[str, str]] = []
        for index, row in enumerate(reader):
            if index >= max_rows:
                break
            rows.append({key or "index": value for key, value in row.items()})
        return rows


def print_table(rows: list[dict[str, str]]) -> None:
    if not rows:
        print("  （无可预览数据）")
        return
    columns = list(rows[0].keys())
    widths = {
        column: min(
            24,
            max(len(column), *(len(str(row.get(column, ""))) for row in rows)),
        )
        for column in columns
    }
    header = " | ".join(column[: widths[column]].ljust(widths[column]) for column in columns)
    print("  " + header)
    print("  " + "-+-".join("-" * widths[column] for column in columns))
    for row in rows:
        print(
            "  "
            + " | ".join(str(row.get(column, ""))[: widths[column]].ljust(widths[column]) for column in columns)
        )


def summarize_report(path: Path) -> None:
    data = read_json(path)
    if data is None:
        print(f"  缺少摘要：{relative(path)}")
        return

    metadata = data.get("metadata", {})
    artifacts = data.get("artifacts", {})
    print(f"  摘要：{relative(path)}")
    if isinstance(metadata, dict):
        for name in [
            "problem",
            "models",
            "input_modes",
            "best_model_by_E_rmse",
            "best_run_by_E_rmse",
            "elapsed_seconds",
        ]:
            if name in metadata:
                print(f"    {name}: {metadata[name]}")
        training = metadata.get("training")
        if isinstance(training, dict) and "checkpoint_reused" in training:
            print(f"    checkpoint_reused: {training['checkpoint_reused']}")
    if isinstance(artifacts, dict):
        counts = {key: len(value) for key, value in artifacts.items() if isinstance(value, list)}
        if counts:
            print(f"    artifacts: {counts}")


def show_task(task_key: str, open_output: bool = False) -> None:
    task = TASKS[task_key]
    print(f"\n===== {task.title} =====")
    print(task.description)
    print(f"输出目录：{relative(task.output_dir)}")

    for report in task.reports:
        summarize_report(report)

    for metric in task.metrics:
        print(f"\n  指标预览：{relative(metric)}")
        print_table(read_csv_rows(metric))

    if task.predictions:
        print("\n  预测表：")
        for prediction in task.predictions:
            marker = "存在" if prediction.exists() else "缺失"
            print(f"    [{marker}] {relative(prediction)}")

    if open_output:
        open_directory(task.output_dir)


def open_directory(path: Path) -> None:
    if not path.exists():
        print(f"输出目录不存在，无法打开：{relative(path)}")
        return
    if hasattr(os, "startfile"):
        os.startfile(path)  # type: ignore[attr-defined]
    else:
        subprocess.run(["xdg-open", str(path)], check=False)


def list_tasks() -> None:
    print("可用任务：")
    for task in TASKS.values():
        deps = f"；依赖：{', '.join(task.depends)}" if task.depends else ""
        scripts = ", ".join(relative(script) for script in task.scripts)
        print(f"- {task.key}: {task.title}{deps}")
        print(f"  {task.description}")
        print(f"  脚本：{scripts}")
    print("\n组合别名：main = 1,2,3,4；all = 1,2,3,4,3-analysis")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="选择性运行或展示 2025 光伏日前预测项目的工程链路结果。",
    )
    parser.add_argument("--list", action="store_true", help="列出可运行任务和依赖关系。")
    parser.add_argument("--run", nargs="+", help="运行任务，例如 1、2,3、4、3-analysis、main 或 all。")
    parser.add_argument("--show", nargs="+", help="展示任务已有输出，不触发训练。")
    parser.add_argument("--parallel", action="store_true", help="并行运行互不依赖的任务。")
    parser.add_argument("--dry-run", action="store_true", help="只打印运行计划，不执行脚本。")
    parser.add_argument("--open-output", action="store_true", help="展示后打开对应 outputs 目录。")
    parser.add_argument("--force-retrain", action="store_true", help="传入 PV_FORCE_RETRAIN=1，强制模型重训。")
    parser.add_argument("--epochs", help="传入 PV_FORECAST_EPOCHS。")
    parser.add_argument("--patience", help="传入 PV_FORECAST_PATIENCE。")
    parser.add_argument("--batch-size", help="传入 PV_FORECAST_BATCH_SIZE。")
    parser.add_argument("--hidden-dim", help="传入 PV_FORECAST_HIDDEN_DIM。")
    parser.add_argument("--q4-modes", help="传入 PV_Q4_MODES，例如 nwp,lmd,mixed 或 all。")
    parser.add_argument("--q4-models", help="传入 PV_Q4_MODELS，例如 FusionModel 或 all。")
    parser.add_argument("--q4-fast", action="store_true", help="传入 PV_Q4_SAVE_RUN_DIAGNOSTICS=0，加快局地校正链路刷新。")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        if args.list:
            list_tasks()

        run_keys = parse_task_selection(args.run)
        show_keys = parse_task_selection(args.show)

        if run_keys:
            execute_tasks(run_keys, args)

        for task_key in show_keys:
            show_task(task_key, open_output=args.open_output)

        if not args.list and not run_keys and not show_keys:
            parser.print_help()
        return 0
    except Exception as exc:
        print(f"错误：{exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
